Repository FC-Palette/Palette-BE, pull requests merged in 2023-10, with the labels that each got.

#52 [Feat] #44 공동구매, 중고거래에서 이미지 사용코드 추가 구현완료
  src/main/java/fc/server/palette/_common/s3/S3ImageUploader.java
  src/main/java/fc/server/palette/purchase/controller/PurchaseController.java
  src/main/java/fc/server/palette/purchase/dto/request/EditOfferDto.java
  src/main/java/fc/server/palette/purchase/dto/request/GroupPurchaseOfferDto.java
  src/main/java/fc/server/palette/purchase/dto/request/RemoveImageDto.java
  src/main/java/fc/server/palette/purchase/repository/PurchaseMediaRepository.java
  src/main/java/fc/server/palette/purchase/service/PurchaseService.java
  src/main/java/fc/server/palette/secondhand/controller/SecondhandController.java
  src/main/java/fc/server/palette/secondhand/dto/request/CreateProductDto.java
  src/main/java/fc/server/palette/secondhand/dto/request/EditProductDto.java
  src/main/java/fc/server/palette/secondhand/repository/SecondhandMediaRepository.java
  src/main/java/fc/server/palette/secondhand/service/SecondhandService.java
Labels: ✨ Feature

#60 [Refactor] #59 : TokenProvider, AuthController 수정
  src/main/java/fc/server/palette/member/auth/Controller/AuthController.java
  src/main/java/fc/server/palette/member/auth/jwt/TokenProvider.java
Labels: 🔨 Refactor

#62 [Refactor] #61 같이성장해요 수정
  src/main/java/fc/server/palette/chat/controller/ChatController.java
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingDetailDto.java
  src/main/java/fc/server/palette/meeting/entity/type/Day.java
  src/main/java/fc/server/palette/meeting/repository/ApplicationRepository.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
  src/main/java/fc/server/palette/member/entity/type/Job.java
  src/main/resources/db/data.sql
Labels: 🔨 Refactor

#64 [Refactor] #63 같이 성장해요 수정
  src/main/java/fc/server/palette/_common/s3/S3ImageUploader.java
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/dto/request/MeetingCreateDto.java
  src/main/java/fc/server/palette/meeting/dto/request/MeetingUpdateDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingDetailDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingListDto.java
  src/main/java/fc/server/palette/meeting/entity/Meeting.java
  src/main/java/fc/server/palette/meeting/entity/type/Day.java
  src/main/java/fc/server/palette/meeting/entity/type/Week.java
  src/main/java/fc/server/palette/meeting/repository/BookmarkRepository.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
  src/main/java/fc/server/palette/member/entity/type/Sex.java
Labels: 🔨 Refactor

#68 [Refactor] #67 채팅 보내기 및 채팅방 로직 개선
  src/main/java/fc/server/palette/chat/controller/ChatController.java
  src/main/java/fc/server/palette/chat/dto/request/ChatMessageDto.java
  src/main/java/fc/server/palette/chat/repository/ChatRoomRepository.java
  src/main/java/fc/server/palette/chat/service/ChatRoomService.java
Labels: 🔨 Refactor

#74 [Fix] #13 마이페이지 추가정보전달을 위한 수정 및 기타
  src/main/java/fc/server/palette/meeting/repository/ApplicationRepository.java
  src/main/java/fc/server/palette/member/controller/MemberController.java
  src/main/java/fc/server/palette/member/dto/response/MemberMyPageDto.java
  src/main/java/fc/server/palette/member/repository/FollowRepository.java
  src/main/java/fc/server/palette/member/service/MemberService.java
  src/main/java/fc/server/palette/purchase/repository/PurchaseParticipantRepository.java
Labels: ✨ Feature

#75 [Fix] #13 S3이미지업로드기능 수정기능에 추가
  src/main/java/fc/server/palette/member/controller/MemberController.java
  src/main/java/fc/server/palette/member/dto/request/MemberProfileDto.java
  src/main/java/fc/server/palette/member/entity/Member.java
  src/main/java/fc/server/palette/member/entity/type/Job.java
  src/main/java/fc/server/palette/member/service/MemberService.java
Labels: 🐛 BugFix

#76 [Feature] #71같이 성장해요 api 추가구현
  src/main/java/fc/server/palette/_common/exception/message/ExceptionMessage.java
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
Labels: ✨ Feature

#89 [Refactor] #83 팔로우관계관련 예외처리 수정및 기능추가
  src/main/java/fc/server/palette/_common/exception/message/ExceptionMessage.java
  src/main/java/fc/server/palette/member/dto/response/FollowInfoDto.java
  src/main/java/fc/server/palette/member/service/MemberService.java
Labels: 🐛 BugFix, ✨ Feature

#94 [Fix] #83 예외처리부분 추가수정
  src/main/java/fc/server/palette/_common/exception/message/ExceptionMessage.java
  src/main/java/fc/server/palette/member/service/MemberService.java
Labels: 🐛 BugFix

#80 [Refactor] #77 같이 성장해요 detail수정 예외처리
  src/main/java/fc/server/palette/_common/exception/message/ExceptionMessage.java
  src/main/java/fc/server/palette/meeting/repository/ApplicationRepository.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
Labels: 🔨 Refactor
