Repository FC-Palette/Palette-BE, pull requests merged in 2023-09, with the labels that each got.

#3 [Feat] #2 엔티티 초기 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/fc/server/palette/PaletteApplication.java
  src/main/java/fc/server/palette/_common/auditing/BaseEntity.java
  src/main/java/fc/server/palette/chat/entity/Emoticon.java
  src/main/java/fc/server/palette/chat/entity/Message.java
  src/main/java/fc/server/palette/chat/entity/Participant.java
  src/main/java/fc/server/palette/chat/entity/Room.java
  src/main/java/fc/server/palette/chat/entity/type/Type.java
  src/main/java/fc/server/palette/meeting/entity/Application.java
  src/main/java/fc/server/palette/meeting/entity/Bookmark.java
  src/main/java/fc/server/palette/meeting/entity/Media.java
  src/main/java/fc/server/palette/meeting/entity/Meeting.java
  src/main/java/fc/server/palette/meeting/entity/type/AcceptType.java
  src/main/java/fc/server/palette/meeting/entity/type/Age.java
  src/main/java/fc/server/palette/meeting/entity/type/Category.java
  src/main/java/fc/server/palette/meeting/entity/type/Day.java
  src/main/java/fc/server/palette/meeting/entity/type/Status.java
  src/main/java/fc/server/palette/meeting/entity/type/Type.java
  src/main/java/fc/server/palette/meeting/entity/type/Week.java
  src/main/java/fc/server/palette/member/entity/Follow.java
  src/main/java/fc/server/palette/member/entity/Member.java
  src/main/java/fc/server/palette/member/entity/type/Job.java
  src/main/java/fc/server/palette/member/entity/type/Position.java
  src/main/java/fc/server/palette/member/entity/type/Sex.java
  src/main/java/fc/server/palette/purchase/entity/Bookmark.java
  src/main/java/fc/server/palette/purchase/entity/Media.java
  src/main/java/fc/server/palette/purchase/entity/Purchase.java
  src/main/java/fc/server/palette/purchase/entity/type/Category.java
  src/main/java/fc/server/palette/purchase/entity/type/ClosingType.java
  src/main/java/fc/server/palette/secondhand/entity/Bookmark.java
  src/main/java/fc/server/palette/secondhand/entity/Media.java
  src/main/java/fc/server/palette/secondhand/entity/Secondhand.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/env.yml
  src/test/java/fc/server/palette/PaletteApplicationTests.java
Labels: ✨ Feature, ⚙️ Setting

#12 [Feat] #6 로그인기능 구현및 수정
  src/main/java/fc/server/palette/_common/config/SecurityConfig.java
  src/main/java/fc/server/palette/member/auth/Controller/AuthController.java
  src/main/java/fc/server/palette/member/auth/CustomUserDetailService.java
  src/main/java/fc/server/palette/member/auth/CustomUserDetails.java
  src/main/java/fc/server/palette/member/auth/dto/LoginDto.java
  src/main/java/fc/server/palette/member/auth/dto/TokenDto.java
  src/main/java/fc/server/palette/member/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/fc/server/palette/member/auth/jwt/TokenProvider.java
  src/main/java/fc/server/palette/member/auth/util/SecurityUtil.java
  src/main/java/fc/server/palette/member/repository/MemberRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/db/data.sql
Labels: ✨ Feature

#16 [Feat] #14 공통 응답 및 에러 핸들링
  src/main/java/fc/server/palette/_common/aop/ResponseHandler.java
  src/main/java/fc/server/palette/_common/exception/Exception400.java
  src/main/java/fc/server/palette/_common/exception/Exception401.java
  src/main/java/fc/server/palette/_common/exception/Exception403.java
  src/main/java/fc/server/palette/_common/exception/Exception404.java
  src/main/java/fc/server/palette/_common/exception/Exception500.java
  src/main/java/fc/server/palette/_common/exception/handler/MyExceptionHandler.java
  src/main/java/fc/server/palette/_common/exception/message/ExceptionMessage.java
  src/main/java/fc/server/palette/_common/util/ApiUtils.java
Labels: ✨ Feature, ⚙️ Setting

#18 [Feat] #4 같이 성장해요 CRUD 및 일부 기능 구현
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/dto/request/ApplicationRequestDto.java
  src/main/java/fc/server/palette/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/fc/server/palette/meeting/dto/request/MeetingUpdateRequestDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingDetailResponseDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingListResponseDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingMemberResponseDto.java
  src/main/java/fc/server/palette/meeting/entity/Application.java
  src/main/java/fc/server/palette/meeting/entity/Bookmark.java
  src/main/java/fc/server/palette/meeting/entity/Media.java
  src/main/java/fc/server/palette/meeting/entity/Meeting.java
  src/main/java/fc/server/palette/meeting/entity/type/AcceptType.java
  src/main/java/fc/server/palette/meeting/entity/type/Age.java
  src/main/java/fc/server/palette/meeting/entity/type/Category.java
  src/main/java/fc/server/palette/meeting/entity/type/Day.java
  src/main/java/fc/server/palette/meeting/entity/type/Status.java
  src/main/java/fc/server/palette/meeting/entity/type/Type.java
  src/main/java/fc/server/palette/meeting/entity/type/Week.java
  src/main/java/fc/server/palette/meeting/service/ApplicationRepository.java
  src/main/java/fc/server/palette/meeting/service/BookmarkRepository.java
  src/main/java/fc/server/palette/meeting/service/MediaRepository.java
  src/main/java/fc/server/palette/meeting/service/MeetingMediaService.java
  src/main/java/fc/server/palette/meeting/service/MeetingRepository.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
  src/main/java/fc/server/palette/member/entity/type/Job.java
  src/main/java/fc/server/palette/member/entity/type/Position.java
  src/main/java/fc/server/palette/member/entity/type/Sex.java
Labels: ✨ Feature, 🔨 Refactor

#21 [Refactor] #20 오류 메시지 처리 및 패키지 추가
  src/main/java/fc/server/palette/_common/exception/message/ExceptionMessage.java
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/repository/ApplicationRepository.java
  src/main/java/fc/server/palette/meeting/repository/BookmarkRepository.java
  src/main/java/fc/server/palette/meeting/repository/MediaRepository.java
  src/main/java/fc/server/palette/meeting/repository/MeetingRepository.java
  src/main/java/fc/server/palette/meeting/service/MeetingMediaService.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
Labels: 🔨 Refactor

#24 [Feat] #19 같이성장해요 주최자 승인대기목록 확인 및 승인/거절 기능
  src/main/java/fc/server/palette/_common/exception/message/ExceptionMessage.java
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/dto/response/WaitingParticipateMemberResponseDto.java
  src/main/java/fc/server/palette/meeting/entity/Application.java
  src/main/java/fc/server/palette/meeting/entity/Meeting.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
Labels: ✨ Feature

#23 [Feat] #22 채팅 리스트 구현
  src/main/java/fc/server/palette/_common/util/WebSocketEventListener.java
  src/main/java/fc/server/palette/chat/controller/ChatController.java
  src/main/java/fc/server/palette/chat/dto/response/ChatRoomListResponseDto.java
  src/main/java/fc/server/palette/chat/entity/ChatRoom.java
  src/main/java/fc/server/palette/chat/repository/ChatMessageRepository.java
  src/main/java/fc/server/palette/chat/repository/ChatRoomRepository.java
  src/main/java/fc/server/palette/chat/service/ChatRoomService.java
  src/main/java/fc/server/palette/chat/service/ChatService.java
Labels: ✨ Feature

#29 [Feat] #13: 마이페이지 CRUD 기능구현
  src/main/java/fc/server/palette/member/controller/MemberController.java
  src/main/java/fc/server/palette/member/dto/request/FollowRequestDto.java
  src/main/java/fc/server/palette/member/dto/request/MemberProfileDto.java
  src/main/java/fc/server/palette/member/dto/response/FollowInfoDto.java
  src/main/java/fc/server/palette/member/dto/response/MemberMyPageDto.java
  src/main/java/fc/server/palette/member/entity/Follow.java
  src/main/java/fc/server/palette/member/entity/Member.java
  src/main/java/fc/server/palette/member/entity/type/Job.java
  src/main/java/fc/server/palette/member/entity/type/Position.java
  src/main/java/fc/server/palette/member/entity/type/Sex.java
  src/main/java/fc/server/palette/member/repository/BuildingRepository.java
  src/main/java/fc/server/palette/member/repository/FollowRepository.java
  src/main/java/fc/server/palette/member/repository/MemberRepository.java
  src/main/java/fc/server/palette/member/repository/RoomRepository.java
  src/main/java/fc/server/palette/member/repository/TenantRepository.java
  src/main/java/fc/server/palette/member/service/MemberService.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature

#32 [Feat] #26 중고거래 CRUD구현
  src/main/java/fc/server/palette/member/auth/CustomUserDetails.java
  src/main/java/fc/server/palette/purchase/controller/PurchaseController.java
  src/main/java/fc/server/palette/purchase/entity/Purchase.java
  src/main/java/fc/server/palette/purchase/entity/type/Category.java
  src/main/java/fc/server/palette/secondhand/controller/SecondhandController.java
  src/main/java/fc/server/palette/secondhand/dto/request/CreateProductDto.java
  src/main/java/fc/server/palette/secondhand/dto/request/EditProductDto.java
  src/main/java/fc/server/palette/secondhand/dto/response/ProductDto.java
  src/main/java/fc/server/palette/secondhand/dto/response/ProductListDto.java
  src/main/java/fc/server/palette/secondhand/entity/Secondhand.java
  src/main/java/fc/server/palette/secondhand/repository/SecondhandBookmarkRepository.java
  src/main/java/fc/server/palette/secondhand/repository/SecondhandMediaRepository.java
  src/main/java/fc/server/palette/secondhand/repository/SecondhandRespository.java
  src/main/java/fc/server/palette/secondhand/service/SecondhandService.java
Labels: ✨ Feature

#30 [Feat] #27 채팅 정보 조회, 퇴장 기능 구현
  src/main/java/fc/server/palette/chat/controller/ChatController.java
  src/main/java/fc/server/palette/chat/dto/request/ChatRoomNoticeRequestDto.java
  src/main/java/fc/server/palette/chat/dto/response/ChatRoomDetailContentResponseDto.java
  src/main/java/fc/server/palette/chat/dto/response/ChatRoomDetailResponseDto.java
  src/main/java/fc/server/palette/chat/dto/response/ChatRoomListResponseDto.java
  src/main/java/fc/server/palette/chat/dto/response/ChatRoomNoticeListResponseDto.java
  src/main/java/fc/server/palette/chat/entity/ChatRoom.java
  src/main/java/fc/server/palette/chat/entity/type/ChatMessageType.java
  src/main/java/fc/server/palette/chat/service/ChatRoomService.java
  src/main/java/fc/server/palette/chat/service/ChatService.java
Labels: ✨ Feature

#37 [Feat] #35 yml 추가
  src/main/resources/application-prod.yml
Labels: ✨ Feature, ⚙️ Setting

#40 [Chore]#39 더미데이터 추가
  src/main/resources/db/data.sql
Labels: ⚙️ Setting

#38 [Refactor] #34 같이성장해요 수정
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingDetailResponseDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingListResponseDto.java
  src/main/java/fc/server/palette/meeting/entity/Meeting.java
  src/main/java/fc/server/palette/meeting/entity/type/AcceptType.java
  src/main/java/fc/server/palette/meeting/entity/type/Day.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
  src/main/java/fc/server/palette/member/entity/type/Job.java
  src/main/java/fc/server/palette/member/entity/type/Sex.java
  src/main/resources/db/data.sql
Labels: 🔨 Refactor

#46 [Fix] #45 SecurityConfig 수정
  src/main/java/fc/server/palette/_common/config/SecurityConfig.java
Labels: 🐛 BugFix

#51 [Refactor] #41같이 성장해요 수정
  src/main/java/fc/server/palette/meeting/controller/MeetingController.java
  src/main/java/fc/server/palette/meeting/dto/request/ApplicationDto.java
  src/main/java/fc/server/palette/meeting/dto/request/MeetingCreateDto.java
  src/main/java/fc/server/palette/meeting/dto/request/MeetingUpdateDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingDetailDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingListDto.java
  src/main/java/fc/server/palette/meeting/dto/response/MeetingMemberDto.java
  src/main/java/fc/server/palette/meeting/dto/response/WaitingParticipateMemberDto.java
  src/main/java/fc/server/palette/meeting/entity/Meeting.java
  src/main/java/fc/server/palette/meeting/service/MeetingMediaService.java
  src/main/java/fc/server/palette/meeting/service/MeetingService.java
  src/main/resources/db/data.sql
Labels: 🔨 Refactor
